name: Run Tests on Pull Request

on:
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write
            issues: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Checkout submodules
              run: git submodule update --init --recursive

            - name: Set up C++ environment
              run: |
                  sudo apt-get update
                  sudo apt-get install -y g++ cmake build-essential

            - name: Build project
              run: |
                  # find the Makefile
                  makefile=$(find . -name Makefile)
                  if [ -z "$makefile" ]; then
                      echo "Makefile not found"
                      exit 1
                  fi

                  # build the project
                  make

            - name: Run tests
              id: run-tests
              run: make test

            - name: Post test results
              if: always()
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const runId = process.env.GITHUB_RUN_ID;
                      const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}`;
                      const testStatus = steps['run-tests'].outcome === 'success' ? '✅' : '❌';
                      const conclusion = steps['run-tests'].outcome === 'success' ? 'All tests passed successfully!' : 'Some tests failed. Please check the logs for more details.';
                      const logsLink = `[View logs](${runUrl})`;

                      let body = `
                      ### Test Results

                      **Status:** ${testStatus}

                      **Conclusion:** ${conclusion}

                      ${logsLink}

                      ---
                      This comment was automatically generated by [GitHub Actions](https://github.com/features/actions).
                      `;

                      github.rest.issues.createComment({
                      issue_number: context.issue.number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      body: body
                      });
